2020-10-02 20:32:05,999 ERROR: Exception on /age/target.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 51, in detect_age
    faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/home/mmaitland300/flask/webproject/deploy.prototxt" in function 'ReadProtoFromTextFile'

2020-10-02 20:55:39,979 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:55:40,009 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:55:40,009 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:04:53,886 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:04:53,898 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:04:53,898 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:11:04,743 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:11:04,767 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:11:04,767 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:12:16,996 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:12:17,008 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:12:17,008 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:13:19,329 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:13:19,348 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:13:19,348 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 21:17:08,670 ERROR: Exception on /age/face.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 90, in detect_age
    swapRB=False)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

2020-10-02 21:17:08,670 ERROR: Exception on /age/face.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 90, in detect_age
    swapRB=False)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

