2020-09-21 01:20:27,775 ERROR: Exception on /matgur [GET] [in /home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask_app/webproject/app/flaskgur/flaskgur.py", line 117, in upload_pic
    return render_template('flaskgur/upload.html', pics=get_last_pics())
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mmaitland300/flask_app/webproject/app/templates/flaskgur/upload.html", line 5, in top-level template code
    {% extends "flaskgur/base.html" %}
  File "/home/mmaitland300/flask_app/webproject/app/templates/flaskgur/base.html", line 35, in top-level template code
    {% block content %}
  File "/home/mmaitland300/flask_app/webproject/app/templates/flaskgur/upload.html", line 31, in block "content"
    <a class="dropdown-item" href= "{{ url_for('flaskgur.enhance', filename=pic) }}">Enhance</a>
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'flaskgur.enhance' with values ['filename']. Did you mean 'flaskgur.enhan' instead?
2020-09-21 01:20:47,176 INFO: Matts brain startup [in /home/mmaitland300/flask_app/webproject/app/__init__.py:95]
2020-09-21 01:20:47,187 INFO: Matts brain startup [in /home/mmaitland300/flask_app/webproject/app/__init__.py:95]
2020-09-21 01:20:47,187 INFO: Matts brain startup [in /home/mmaitland300/flask_app/webproject/app/__init__.py:95]
2020-09-22 20:40:44,548 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-22 20:40:44,563 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-22 20:40:44,563 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-27 18:03:37,509 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-27 18:03:37,548 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-27 18:03:37,548 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-27 18:03:39,712 ERROR: Exception on /auth/login [GET] [in /home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/auth/views.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mmaitland300/flask/webproject/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/mmaitland300/flask/webproject/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "html"
    {%- block html %}
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "head"
    {%- block head %}
  File "/home/mmaitland300/.virtualenvs/flask/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 8, in block "styles"
jinja2.exceptions.UndefinedError: 'bootstrap_find_resource' is undefined
