2020-10-08 20:44:42,408 ERROR: Exception on /fswap [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/faceswap/faceswap.py", line 86, in swapface
    swap(filename1, filename2)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 318, in swap
    src_points, src_shape, src_face = select_face(src_img)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 37, in select_face
    faces = face_detection(im)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 18, in face_detection
    faces = detector(img, upsample_times)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.fhog_object_detector, image: array, upsample_num_times: int=0) -> _dlib_pybind11.rectangles

Invoked with: <_dlib_pybind11.fhog_object_detector object at 0x7c86834fddc0>, None, 1
2020-10-08 20:48:25,759 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:48:25,770 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:48:25,770 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:48:45,081 ERROR: Exception on /fswap [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/faceswap/faceswap.py", line 88, in swapface
    swap(filename1, filename2)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 318, in swap
    src_points, src_shape, src_face = select_face(src_img)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 37, in select_face
    faces = face_detection(im)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 18, in face_detection
    faces = detector(img, upsample_times)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.fhog_object_detector, image: array, upsample_num_times: int=0) -> _dlib_pybind11.rectangles

Invoked with: <_dlib_pybind11.fhog_object_detector object at 0x7ad32f426e30>, None, 1
2020-10-08 20:48:45,081 ERROR: Exception on /fswap [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/faceswap/faceswap.py", line 88, in swapface
    swap(filename1, filename2)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 318, in swap
    src_points, src_shape, src_face = select_face(src_img)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 37, in select_face
    faces = face_detection(im)
  File "/home/mmaitland300/flask/webproject/app/faceswap/swap.py", line 18, in face_detection
    faces = detector(img, upsample_times)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.fhog_object_detector, image: array, upsample_num_times: int=0) -> _dlib_pybind11.rectangles

Invoked with: <_dlib_pybind11.fhog_object_detector object at 0x7ad32f426e30>, None, 1
2020-10-08 20:50:45,349 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:50:45,376 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:50:45,376 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:51:00,637 ERROR: Exception on /fswap [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/faceswap/faceswap.py", line 89, in swapface
    image = Image.open(current_app.config['IMGDIR'] + 'result.jpg')
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/faceswap/imagesresult.jpg'
2020-10-08 20:51:00,637 ERROR: Exception on /fswap [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/faceswap/faceswap.py", line 89, in swapface
    image = Image.open(current_app.config['IMGDIR'] + 'result.jpg')
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'app/faceswap/imagesresult.jpg'
2020-10-08 20:51:54,519 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:51:54,530 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
2020-10-08 20:51:54,530 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:99]
