2020-10-20 18:55:00,398 ERROR: Exception on /faceupload [POST] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/projectmatt/app/faceswap/faceswap.py", line 48, in upload
    upload.save(destination)
  File "/opt/miniconda3/lib/python3.8/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/home/mmaitland300/flask/projectmatt/images'
2020-10-20 18:56:07,019 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 18:56:07,032 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 18:56:07,032 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 18:56:23,782 ERROR: Exception on /faceupload [POST] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/projectmatt/app/faceswap/faceswap.py", line 48, in upload
    upload.save(destination)
  File "/opt/miniconda3/lib/python3.8/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/home/mmaitland300/flask/projectmatt/images'
2020-10-20 18:56:23,782 ERROR: Exception on /faceupload [POST] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/projectmatt/app/faceswap/faceswap.py", line 48, in upload
    upload.save(destination)
  File "/opt/miniconda3/lib/python3.8/site-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/home/mmaitland300/flask/projectmatt/images'
2020-10-20 18:57:43,216 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 18:57:43,233 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 18:57:43,233 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:00:29,275 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:00:29,288 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:00:29,288 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:06:09,064 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:06:09,075 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:06:09,075 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:08:36,968 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:08:36,979 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:08:36,979 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:12:18,049 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:12:18,063 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:12:18,063 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:16:06,720 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:16:06,733 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:16:06,733 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:102]
2020-10-20 19:16:26,211 ERROR: Exception on /faceupload [POST] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/projectmatt/app/faceswap/faceswap.py", line 74, in upload
    return render_template("faceswap/fgallery.html", warning="Only upload two images!")
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: faceswap/fgallery.html
