2020-10-06 15:24:05,733 ERROR: Exception on /send_contact [POST] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/flask/webproject/app/main/views.py", line 295, in send_contact
    response = sg.send(message)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/sendgrid/base_interface.py", line 62, in send
    return self.client.mail.send.post(request_body=message)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/python_http_client/client.py", line 277, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/python_http_client/client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/mmaitland300/flask/webproject/app/main/views.py", line 300, in send_contact
    print(e.message)
AttributeError: 'UnauthorizedError' object has no attribute 'message'
2020-10-06 15:24:32,562 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:24:32,574 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:24:32,574 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:29:42,852 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:29:42,873 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:29:42,873 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:44:32,838 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:44:32,856 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-06 15:44:32,856 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
